// client/src/views/LoginForm.vue
<template>
  <div class="login-form">
    <form @submit.prevent="handleSubmit">
      <input
        v-model="username"
        type="text"
        autocomplete="username"
        placeholder="username"
      >
      <input
        v-model="password"
        type="password"
        autocomplete="current-password"
        placeholder="password"
      >
      <button type="submit">
        Login
      </button>
    </form>
  </div>
</template>

<script>
import { mapActions } from 'vuex'

export default {
  name: 'LoginForm',
  data() {
    return {
      username: '',
      password: '',
    }
  },
  methods: {
    handleSubmit: function() {
      this.getAuthToken({
        username: this.username,
        password: this.password
      })
    },
    ...mapActions(['getAuthToken'])
  }
}
</script>

<style lang="scss" scoped>
</style>

// src/components/LoginForm.jsx
import React, { useState } from "react";
import { useDispatch } from "react-redux";

import { postAuthToken } from "../store/actions/Auth";

function LoginForm(props) {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const dispatch = useDispatch();

  const handleSubmit = (event) => {
    dispatch(postAuthToken(username, password));
    event.preventDefault();
  };

  return (
    <>
      <h2>Login</h2>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          autoComplete="username"
          placeholder="username"
          value={username}
          onChange={(event) => setUsername(event.target.value)}
        />
        <input
          type="password"
          autoComplete="password"
          placeholder="password"
          value={password}
          onChange={(event) => setPassword(event.target.value)}
        />
        <button type="submit">Login</button>
      </form>
    </>
  );
}

export default LoginForm;
